### PR TITLE
LES branch changes

### PR DESCRIPTION
**Pull request by zah**

### CODE REVIEW

**Review by yglukhov — APPROVED** [review]
LGTM, but I'd refrain from adding a public `>>` operator. I prefer some `proc read[T](rlp: Rlp, dest: var T)` instead.

**Comment by zah** [comment]
`rlp.read(var)` looks potentially confusing to me. If I'm new to the API, I would assume that something from `var` is being read into the RLP. `var.readFrom(rlp)` would be better, but `>>` already has a similar established meaning in C++ and Ruby, so I think it's relatively clear.

**Comment by yglukhov** [comment]
Well it could be `rlp.readInto(var)` to be more meaningful. Dunno, maybe it's just me, but I really don't like introducing random operators, besides we're targeting more python programmers than cpp or ruby :)

**Comment by yglukhov** [comment]
Merging, leaving `>>` to future discussions

**Pull request merged**
